### ISSUE TITLE
PHAS gate expander?

### ISSUE THREAD

**Issue by gderosa** [artiste-qb-net/qubiter#14]
When I try to invoke `Qubiter_to_IBMqasm2()` it fails when there are PHAS gates in the English file.

Do we have a PHAS expander that translates into gates available on IBM etc.? Just like we have expanders for DiagUnitary and Multiplexor...

**Comment by rrtucci** [comment]
Yes, you can first use CGateExpander. That is supposed to expand the
controlled phase gates if it works as expected.

**Comment by gderosa** [comment]
I did use `CGateExpander` but it leaves the PHAS'es unchanged... The file is pretty large, but I'll see if I can reproduce with a smaller one.

[csd_X4_5_eng.txt](https://github.com/artiste-qb-net/qubiter/files/1666356/csd_X4_5_eng.txt)

**Comment by rrtucci** [comment]
I looked at it. These are all global phases, not controlled ones. Looks
like the controlled ones have been decomposed. I don't think IBMqasm
simulator has global phases as gates. They can't be measured physically but
they are sometimes useful in numeric tests

**Comment by gderosa** [comment]
They are not controlled but they are not global either i.e. they act on one qubit only, not on the the "compound wave function" so to speak... I'm not 100% sure they are irrelevant, but I'll check...

**Comment by rrtucci** [comment]
They are global. I attached them to one of the qubits, because I had to
attach them to something :). However, it doesn't matter which qubit they
are attached to.  I can change Qubiter_to_IBMqasm2 so that it aborts at
controlled phases but comments out global phases and continues past them.
Would that satisfy you?

**Comment by rrtucci** [comment]
I did what I promised to do in my last message.  Hope it works.

**Comment by gderosa** [comment]
Thank you, that would work!
